databases:
  - name: viewmaster-db
    plan: free
    databaseName: viewmaster
    user: viewmaster

services:
  - type: web
    plan: free
    name: viewmaster
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn viewmaster.wsgi:application --chdir viewmaster --bind 0.0.0.0:$PORT'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: viewmaster-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: '3.13.0'
      - key: WEB_CONCURRENCY
        value: 4
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: AWS_S3_VIDEO_KEY_PREFIX
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
